### ISSUE TITLE
Nodejs doesn't support XMLHttpRequest

### ISSUE THREAD

**Issue by Helical-x** [jinaga/jinaga.js#94]
NodeJs raise error:

**ReferenceError: XMLHttpRequest is not defined**

I suggest to get rid of  XMLHttpRequest and use fetch which is supported by browsers too. So users can implement the library in Nodejs processes.

**Comment by michaellperry** [comment]
Thank you. That's a good use case. I'll prioritize it.

**Comment by michaellperry** [comment]
Fixed in jinaga@6.2.0. I also added an alias `JinagaClient` so that you don't have to use `JinagaBrowser` in a Node app.

Tested both in browser and in Node. Please let me know if you run into any issues. And thanks!

**Comment by Helical-x** [comment]
> Fixed in jinaga@6.2.0. I also added an alias `JinagaClient` so that you don't have to use `JinagaBrowser` in a Node app.
> 
> Tested both in browser and in Node. Please let me know if you run into any issues. And thanks!

Excellent. I'll do some testing and keep you informed. Thanks
