### ISSUE TITLE
Simplify join syntax

### ISSUE THREAD

**Issue by floyd-may** [jinaga/jinaga.js#99]
The `.ofType(...).join(...)` syntax for specifications can be much simpler. The way it works right now, it requires the developer to "invert" the join, rather than being able to directly select successor facts from a given fact. Here's an example straight from the docs:

```typescript
const postsInSite = model.given(Site).match((site, facts) =>
  facts.ofType(Post)
    .join(post => post.site, site)
    .select(post => ({
      hash: j.hash(post),
      titles: facts.ofType(PostTitle)
        .join(title => title.post, post)
        .select(title => title.value)
    }))
);
```

I think this could be both clearer and simpler by allowing someone to directly select _successors_:

```typescript
const postsInSite = model.given(Site).match((site, facts) =>
  site
    .successors<Post>(post => post.site)
    .select(post => ({
      hash: j.hash(post),
      titles: post
        .successors<PostTitle>(title => title.post)
        .select(title => title.value)
    }))
);
```

This assumes that the functions within `.match(...)` wrap a type like this around each fact type (implemented via proxy):

```typescript
type SpecificationFact<T> = T & {
  /*
   * Gets successors of type U where fact(s) returned by predecessorSelector match this fact
   */
  successors<U>(predecessorSelector: (fact: U) => T): Specification<U>;
}
```

**Comment by michaellperry** [comment]
Nice. The syntax as implemented allows for a chain of predecessors on both the left and the right-hand sides. But if you are only going down to successors (as you most often are), then this syntax would be simpler. Let's give it a try.
